### PR TITLE
Add Must* functions for int and string

### PR DESCRIPTION
**Pull request by DataMob**

### CODE REVIEW

**Comment by peterhellberg** [comment]
👎

Libraries should not panic. This should be handled in each applications main.go

```go
if s := env.Get("FOO", ""); s == "" {
  panic("no FOO environment variable!")
}
```

**Comment by ivarg** [comment]
An argument would be that the `Must` line of panicing functions in libraries is part of an established pattern, e.g. in [text/template](https://golang.org/pkg/text/template/#Must).

**Comment by jsageryd** [comment]
Fwiw, my perspective on `panic` is that it is OK to use for things that should never happen, such as say compiling a hard-coded regexp (such that if it fails, there's an error in stdlib). If it's an expected error (e.g. someone misconfigured the service), then handling it gracefully with a normal error message (e.g. `log.Fatal` and friends) is more appropriate. Cf. a user-facing application (cmdline or the like); one would never expect it to explode with a stacktrace if configuration is wrong. One would rather expect an informative error message.

**Comment by ivarg** [comment]
The `env` package offers a convenience behavior for when an environment variable is not present, which is to return a fallback value. Convenience behavior for when an environment variable is not present is it's purpose.

I argue that another occasional desired behavior for when a variable is not present is to stop execution, e.g. when no sensible default value is applicable. As such, it makes sense for `env` to offer functions that satisfy that use case as well.

IMHO this is about offering the user a documented, expected, and desired behavior, and not a question of whether a library should panic. That discussion is about undocumented and unexpected behavior in the face of bad input. And I agree that misconfiguration should never make anything explode.

**Comment by peterhellberg** [comment]
I'd be open to the idea of adding a separate interface with two return
values for each method (T, error). But I firmly believe that a library
should never panic. Returning an error on the other hand is fine in my
opinion.

**Comment by marcusolsson** [comment]
To me, the issue is how to address _required_ env variables to complement handling of _default_ ones.

On returning errors, I'm not sure this:

```
n, err := env.MustString("NAME")
if err != nil {
    log.Fatal("env missing")
}
```

offers that much of an improvement over this:

```
n := os.Getenv("NAME")
if n == "" {
    log.Fatal("env missing")
}
```

Some suggestions:

1. Applications should always specify reasonable defaults (no changes made to `env`).

2. Applications deal with required variables themselves, i.e. writing their own `func mustString(key string) { ... }`, i.e. you're on your own.

3. If we really feel the need for this package to handle required vars, I would suggest adopting a set-based-ish approach like the `FlagSet` in the `flag` package, i.e. `func (vs VarSet) Parse() error` to handle validation in one place.

4. Use a package that provides a support for both required and default vars (my favorite is [envconfig](https://github.com/kelseyhightower/envconfig)).

I actually think the third alternative could turn out pretty nice if done properly.

EDIT: Just to clarify, this would be my order of preference.

**Comment by piaborlin** [comment]
I'm also of the opinion that the API should not panic, if we want `env` package to also support required variables an error should be returned in my opinion. 

But leaving the `env` package as simple as it is could also be one way to go. If adding required variables check maybe  a`Parse()` function could be in place as Marcus suggested.

**Comment by ivarg** [comment]
I will close this PR since there's a lack of support for this feature.

However, for the sake of argument, I must add that whether you _personally_ like it or not, this is a well established idiom in both the standard library and prominent Go projects such as [kubernetes](https://github.com/kubernetes/client-go/blob/master/pkg/apis/rbac/helpers.go#L161), [etcd](https://github.com/coreos/etcd/blob/master/integration/cluster.go#L796), and [prometheus](https://github.com/prometheus/client_golang/blob/3fb8ace93bc4ccddea55af62320c2fd109252880/prometheus/registry.go#L350), where either a `Must` prefix or a `OrDie` postfix to a function name indicates that the function may either panic or log.Fatal (yes, in library code). The behavior is thus explicit and encoded in the name of the function.

This rhymes with other idiomatic conventions in Go, in terms of not having 100% likability in the community as a whole.

**Pull request closed without merging**
